# theme: jekyll-theme-minimal
title: Garcia-Suarez Homepage
description: >-
  Online repository of my research work
url: "https://jgarciasuarez.github.io"
baseurl: ""

# Build settings
markdown: kramdown

remote_theme: "mmistakes/minimal-mistakes" # Ensure this theme is correctly referenced
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

header_pages:
  - index.md
  - about.md
  - projects.md
  - contact.md

sass:
  style: compressed

# Theme settings
minimal_mistakes_skin: dark # or another skin that you prefer
